name: test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8_0
  - cudatoolkit=11.3.1
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - jupyterlab=4.2.5
  - notebook
  - ipykernel
  - ipywidgets
  - requests
  - pip:
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - cvxopt==1.3.2 

